spring:
  application:
    name: cloudstore-distributed-file-system
  profiles:
    active: dev

  # Database Configuration
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/cloudstore_db
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
    sqlite:
      jdbc-url: jdbc:sqlite:/data/local-cache.db
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # Encryption and Security Configuration
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000  # 24 hours
    encryption:
      aes-key-length: 256
      rsa-key-length: 2048

  # File Storage Configuration
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# Logging Configuration
logging:
  level:
    root: INFO
    com.cloudstore: DEBUG
  file:
    path: /logs
    name: /logs/cloudstore.log

# Load Balancer Configuration
loadbalancer:
  strategy: round-robin
  max-retries: 3
  timeout: 5000

# Storage Container Configuration
storage:
  base-dir: /data/files
  chunk-size: 5242880  # 5MB chunks
  replication-factor: 2

# Monitoring Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

# Custom Application Properties
cloudstore:
  storage:
    base-path: /opt/cloudstore/files
    chunk-size: 1MB  # 1 Megabyte chunks

  security:
    soft-delete:
      retention-days: 30
    
    audit:
      log-retention-days: 90

# Logging Configuration
logging:
  level:
    com.cloudstore: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG